-- Boxing coverage baseline (READ ONLY). One jsonb value. Rendered by scripts/coverage/render-baseline.mjs.
-- "canonical" = not merged. Every count is a plain count of stored rows; nothing is estimated.
with
f as (select * from public.boxing_fighters where merged_into_id is null),
fp as (  -- canonical fighter participations in non-cancelled bouts
  select public.boxing_canonical_fighter_id(p.fighter_id) fighter_id, p.bout_id, b.weight_class_id, e.event_date, e.status event_status
  from public.boxing_bout_participants p join public.boxing_bouts b on b.id = p.bout_id join public.boxing_events e on e.id = b.event_id
  where p.participant_status in ('scheduled','confirmed') and b.status is distinct from 'cancelled'),
fb as (select fighter_id, count(distinct bout_id) n, bool_or(weight_class_id is not null) has_division, bool_or(event_date >= current_date) upcoming from fp group by 1),
b as (select * from public.boxing_bouts where status is distinct from 'cancelled'),
bo as (select * from public.boxing_bout_officials where assignment_state in ('assigned','worked')),
r as (select * from public.boxing_bout_results_current),
sc as (select * from public.boxing_scorecards_current),
ev as (select * from public.boxing_events),
sheet as (select * from public.boxing_site_sheet_events()),
sheet_ev as (select distinct ei.event_id, se.promoters from sheet se join public.boxing_event_identities ei on ei.external_id = se.source_event_id and ei.source_id = se.source_id and ei.verification_state <> 'rejected'),
o as (select * from public.boxing_officials where merged_into_id is null)
select jsonb_build_object(
  'generated_at', now(),
  'fighters', jsonb_build_object(
    'canonical', (select count(*) from f),
    'merged_rows', (select count(*) from public.boxing_fighters where merged_into_id is not null),
    'identity_state', (select jsonb_object_agg(identity_state, n) from (select identity_state, count(*) n from f group by 1) x),
    'multi_token_full_name', (select count(*) from f where btrim(display_name) ~ '\s'),
    'single_token_name', (select count(*) from f where btrim(display_name) !~ '\s'),
    'dob', (select count(*) from f where dob is not null),
    'nationality', (select count(*) from f where nationality is not null),
    'birth_country', (select count(*) from f where birth_country is not null),
    'hometown_or_residence', (select count(*) from f where hometown is not null),
    'stance', (select count(*) from f where stance is not null and stance <> 'unknown'),
    'height', (select count(*) from f where height_cm is not null),
    'reach', (select count(*) from f where reach_cm is not null),
    'sex', (select jsonb_object_agg(coalesce(sex, 'null'), n) from (select sex, count(*) n from f group by 1) x),
    'career_status', (select jsonb_object_agg(career_status, n) from (select career_status, count(*) n from f group by 1) x),
    'pro_debut_date', (select count(*) from f where pro_debut_date is not null),
    'with_division_from_a_bout', (select count(*) from fb where has_division),
    'with_upcoming_bout', (select count(*) from fb where upcoming),
    'aliases_rows', (select count(*) from public.boxing_fighter_aliases),
    'fighters_with_alias', (select count(distinct public.boxing_canonical_fighter_id(fighter_id)) from public.boxing_fighter_aliases),
    'identities_by_namespace', (select coalesce(jsonb_object_agg(namespace, n), '{}'::jsonb) from (select namespace, count(*) n from public.boxing_fighter_identities where verification_state <> 'rejected' group by 1) x),
    'wikidata_identity', (select count(distinct public.boxing_canonical_fighter_id(fighter_id)) from public.boxing_fighter_identities where namespace ilike '%wikidata%' and verification_state <> 'rejected'),
    'wikipedia_identity', (select count(distinct public.boxing_canonical_fighter_id(fighter_id)) from public.boxing_fighter_identities where (namespace ilike '%wikipedia%' or external_url ilike '%wikipedia.org%') and verification_state <> 'rejected'),
    'attribute_claims_by_attribute', (select coalesce(jsonb_object_agg(attribute, n), '{}'::jsonb) from (select attribute, count(*) n from public.boxing_fighter_attribute_claims group by 1) x),
    'media_by_review_state', (select coalesce(jsonb_object_agg(review_state, n), '{}'::jsonb) from (select review_state, count(*) n from public.boxing_fighter_media group by 1) x),
    'fighters_with_approved_portrait', (select count(distinct fighter_id) from public.boxing_fighter_media where review_state = 'approved'),
    'career_bouts_distribution', (select jsonb_build_object('0', (select count(*) from f where id not in (select fighter_id from fb)),
        '1', count(*) filter (where n = 1), '2', count(*) filter (where n = 2), '3', count(*) filter (where n = 3), '4_plus', count(*) filter (where n >= 4), 'max', max(n)) from fb),
    'fight_dna_fighters_with_any_available_metric', (select count(distinct s.fighter_id) from public.boxing_fighter_metric_snapshots s where s.status = 'available'),
    'fight_dna_snapshot_status', (select coalesce(jsonb_object_agg(status, n), '{}'::jsonb) from (select status, count(*) n from (select distinct on (fighter_id, metric_key) status from public.boxing_fighter_metric_snapshots order by fighter_id, metric_key, as_of desc) l group by 1) x),
    'identity_review_pending', (select count(*) from public.boxing_identity_review_queue where status = 'pending')),
  'bouts', jsonb_build_object(
    'canonical_non_cancelled', (select count(*) from b),
    'cancelled', (select count(*) from public.boxing_bouts where status = 'cancelled'),
    'by_status', (select jsonb_object_agg(coalesce(status, 'null'), n) from (select status, count(*) n from public.boxing_bouts group by 1) x),
    'on_past_or_complete_events', (select count(*) from b join ev on ev.id = b.event_id where ev.event_date < current_date or ev.status = 'complete'),
    'with_current_result', (select count(*) from b where exists (select 1 from r where r.bout_id = b.id)),
    'past_without_result', (select count(*) from b join ev on ev.id = b.event_id where (ev.event_date < current_date or ev.status = 'complete') and not exists (select 1 from r where r.bout_id = b.id)),
    'result_outcome', (select coalesce(jsonb_object_agg(outcome, n), '{}'::jsonb) from (select outcome, count(*) n from r group by 1) x),
    'result_method', (select coalesce(jsonb_object_agg(coalesce(method, 'null'), n), '{}'::jsonb) from (select method, count(*) n from r group by 1) x),
    'result_with_method', (select count(*) from r where method is not null),
    'stoppage_results', (select count(*) from r where method in ('KO','TKO','RTD','DQ','TECHNICAL_DECISION')),
    'stoppage_with_round', (select count(*) from r where method in ('KO','TKO','RTD','DQ','TECHNICAL_DECISION') and round is not null),
    'stoppage_with_time', (select count(*) from r where method in ('KO','TKO','RTD','DQ','TECHNICAL_DECISION') and time_sec is not null),
    'decisions_with_decision_type', (select count(*) from r where method = 'DECISION' and decision_type is not null),
    'result_revisions_beyond_first', (select count(*) from public.boxing_bout_results where revision > 1),
    'scheduled_rounds', (select count(*) from b where scheduled_rounds is not null),
    'weight_class', (select count(*) from b where weight_class_id is not null),
    'contracted_weight', (select count(*) from b where contracted_weight_lb is not null),
    'with_commission', (select count(*) from b join ev on ev.id = b.event_id where ev.commission_id is not null),
    'with_venue', (select count(*) from b join ev on ev.id = b.event_id where ev.venue_id is not null),
    'with_sheet_promoter', (select count(*) from b where b.event_id in (select event_id from sheet_ev where jsonb_array_length(promoters) > 0)),
    'with_broadcast_notes', (select count(*) from b join ev on ev.id = b.event_id where ev.broadcast_notes is not null),
    'with_referee', (select count(distinct bout_id) from bo where role = 'referee'),
    'with_any_judge', (select count(distinct bout_id) from bo where role = 'judge'),
    'with_three_judges', (select count(*) from (select bout_id from bo where role = 'judge' group by 1 having count(*) >= 3) x),
    'with_current_scorecards', (select count(distinct bout_id) from sc),
    'scorecards_current', (select count(*) from sc),
    'scorecards_with_round_cards', (select count(distinct s.id) from sc s join public.boxing_scorecard_rounds sr on sr.scorecard_id = s.id),
    'point_deductions', (select count(*) from public.boxing_point_deductions),
    'knockdowns', (select count(*) from public.boxing_bout_knockdowns),
    'with_official_weigh_in_both_corners', (select count(*) from (select bout_id from public.boxing_weigh_ins where weigh_in_kind = 'official' group by 1 having count(distinct fighter_id) >= 2) x),
    'with_any_weigh_in', (select count(distinct bout_id) from public.boxing_weigh_ins),
    'with_title_at_stake', (select count(distinct bout_id) from public.boxing_bout_titles where at_stake),
    'with_matched_market', (select count(distinct bout_id) from public.boxing_markets where bout_id is not null),
    'with_linked_video', (select count(distinct bout_id) from public.boxing_video_links where bout_id is not null),
    'punch_stat_rows', (select count(*) from public.boxing_round_punch_stats)),
  'events', jsonb_build_object(
    'total', (select count(*) from ev),
    'by_status', (select jsonb_object_agg(status, n) from (select status, count(*) n from ev group by 1) x),
    'upcoming', (select count(*) from ev where event_date >= current_date and status <> 'cancelled'),
    'past', (select count(*) from ev where event_date < current_date),
    'by_commission', (select coalesce(jsonb_object_agg(coalesce(c.slug, 'none'), n), '{}'::jsonb) from (select commission_id, count(*) n from ev group by 1) x left join public.boxing_commissions c on c.id = x.commission_id),
    'with_venue', (select count(*) from ev where venue_id is not null),
    'with_city', (select count(*) from ev join public.boxing_venues v on v.id = ev.venue_id where v.city is not null),
    'with_country', (select count(*) from ev join public.boxing_venues v on v.id = ev.venue_id where v.country_code is not null),
    'with_start_time', (select count(*) from ev where start_at is not null),
    'with_official_sheet', (select count(distinct event_id) from sheet_ev),
    'with_sheet_promoter', (select count(distinct event_id) from sheet_ev where jsonb_array_length(promoters) > 0),
    'with_any_bout', (select count(distinct event_id) from b),
    'upcoming_with_any_bout', (select count(distinct b.event_id) from b join ev on ev.id = b.event_id where ev.event_date >= current_date),
    'past_with_all_bouts_resulted', (select count(*) from ev where event_date < current_date and exists (select 1 from b where b.event_id = ev.id)
        and not exists (select 1 from b where b.event_id = ev.id and not exists (select 1 from r where r.bout_id = b.id))),
    'with_broadcast_notes', (select count(*) from ev where broadcast_notes is not null),
    'with_linked_video', (select count(distinct event_id) from public.boxing_video_links where event_id is not null),
    'with_card_change_history', (select count(distinct event_id) from public.boxing_card_changes),
    'card_changes_by_type', (select coalesce(jsonb_object_agg(change_type, n), '{}'::jsonb) from (select change_type, count(*) n from public.boxing_card_changes group by 1) x)),
  'venues', jsonb_build_object(
    'total', (select count(*) from public.boxing_venues),
    'with_city', (select count(*) from public.boxing_venues where city is not null),
    'with_region', (select count(*) from public.boxing_venues where region is not null),
    'with_country', (select count(*) from public.boxing_venues where country_code is not null),
    'with_coordinates', (select count(*) from public.boxing_venues where latitude is not null and longitude is not null),
    'same_normalized_name_and_city_groups', (select count(*) from (select lower(regexp_replace(name, '[^A-Za-z0-9]+', '', 'g')), lower(coalesce(city, '')) from public.boxing_venues group by 1, 2 having count(*) > 1) x),
    'without_events', (select count(*) from public.boxing_venues v where not exists (select 1 from ev where ev.venue_id = v.id))),
  'promotions', jsonb_build_object(
    'organizations_by_kind', (select coalesce(jsonb_object_agg(organization_kind, n), '{}'::jsonb) from (select organization_kind, count(*) n from public.boxing_organizations group by 1) x),
    'promoter_names_as_listed_on_sheets', (select public.boxing_site_promoters() -> 'listed_names'),
    'event_organization_roles', (select coalesce(jsonb_object_agg(role, n), '{}'::jsonb) from (select role, count(*) n from public.boxing_event_organizations group by 1) x),
    'promotion_sources', (select coalesce(jsonb_agg(jsonb_build_object('source_key', source_key, 'access_mode', access_mode, 'rights_state', rights_state, 'enabled', enabled) order by source_key), '[]'::jsonb) from public.boxing_sources where source_kind = 'promotion'),
    'promoter_video_channels', (select count(*) from public.boxing_video_channels where source_class = 'promoter_official')),
  'titles', jsonb_build_object(
    'titles_by_organization', (select coalesce(jsonb_object_agg(coalesce(org.slug, 'none'), n), '{}'::jsonb) from (select organization_id, count(*) n from public.boxing_titles group by 1) x left join public.boxing_organizations org on org.id = x.organization_id),
    'titles_by_tier', (select coalesce(jsonb_object_agg(coalesce(tier, 'null'), n), '{}'::jsonb) from (select tier, count(*) n from public.boxing_titles group by 1) x),
    'divisions_with_a_title', (select count(distinct weight_class_id) from public.boxing_titles),
    'reigns', (select count(*) from public.boxing_title_reigns),
    'reigns_by_status', (select coalesce(jsonb_object_agg(status, n), '{}'::jsonb) from (select status, count(*) n from public.boxing_title_reigns group by 1) x),
    'title_events', (select count(*) from public.boxing_title_events),
    'title_events_by_type', (select coalesce(jsonb_object_agg(event_type, n), '{}'::jsonb) from (select event_type, count(*) n from public.boxing_title_events group by 1) x),
    'bout_titles', (select count(*) from public.boxing_bout_titles),
    'ranking_snapshots_by_organization', (select coalesce(jsonb_object_agg(coalesce(org.slug, 'none'), n), '{}'::jsonb) from (select organization_id, count(*) n from public.boxing_ranking_snapshots group by 1) x left join public.boxing_organizations org on org.id = x.organization_id),
    'ranking_entries', (select count(*) from public.boxing_ranking_entries),
    'sanctioning_sources', (select coalesce(jsonb_agg(jsonb_build_object('source_key', source_key, 'access_mode', access_mode, 'rights_state', rights_state, 'enabled', enabled) order by source_key), '[]'::jsonb) from public.boxing_sources where source_kind = 'sanctioning_body'),
    'weight_classes', (select count(*) from public.boxing_weight_classes)),
  'officials', jsonb_build_object(
    'canonical', (select count(*) from o),
    'judges', (select count(*) from o where official_type = 'judge'),
    'referees', (select count(*) from o where official_type = 'referee'),
    'merged_rows', (select count(*) from public.boxing_officials where merged_into_id is not null),
    'external_identities', (select count(*) from public.boxing_official_identities),
    'assignments_active', (select count(*) from bo),
    'assignments_by_role', (select jsonb_object_agg(role, n) from (select role, count(*) n from bo group by 1) x),
    'scorecards_current', (select count(*) from sc),
    'judges_with_a_scorecard', (select count(distinct public.boxing_canonical_official_id(judge_id)) from sc),
    'single_token_names', (select count(*) from o where btrim(display_name) !~ '\s'),
    'leading_non_letter_names', (select count(*) from o where display_name ~ '^[^[:alpha:]]'),
    'review_pending', (select count(*) from public.boxing_official_review_queue where status = 'pending'),
    'judge_dna_available_metrics', (select count(*) from (select distinct on (official_id, metric_key) status, metric_key from public.boxing_official_metric_snapshots order by official_id, metric_key, as_of desc) l where status = 'available' and metric_key like 'judge.%'),
    'referee_dna_available_metrics', (select count(*) from (select distinct on (official_id, metric_key) status, metric_key from public.boxing_official_metric_snapshots order by official_id, metric_key, as_of desc) l where status = 'available' and metric_key like 'referee.%'),
    'officials_with_any_available_metric', (select count(distinct official_id) from public.boxing_official_metric_snapshots where status = 'available')),
  'weigh_ins', jsonb_build_object(
    'rows', (select count(*) from public.boxing_weigh_ins),
    'by_kind', (select coalesce(jsonb_object_agg(weigh_in_kind, n), '{}'::jsonb) from (select weigh_in_kind, count(*) n from public.boxing_weigh_ins group by 1) x),
    'by_verification_state', (select coalesce(jsonb_object_agg(verification_state, n), '{}'::jsonb) from (select verification_state, count(*) n from public.boxing_weigh_ins group by 1) x),
    'with_contracted_weight', (select count(*) from public.boxing_weigh_ins where contracted_weight_lb is not null),
    'missed_weight', (select count(*) from public.boxing_weigh_ins where miss_lb > 0 or status ilike '%miss%'),
    'second_attempts', (select count(*) from public.boxing_weigh_ins where attempt_no > 1)),
  'media', jsonb_build_object(
    'fighter_media_rows', (select count(*) from public.boxing_fighter_media),
    'fighters_with_approved_portrait', (select count(distinct fighter_id) from public.boxing_fighter_media where review_state = 'approved'),
    'fighters_without_approved_portrait', (select count(*) from f where not exists (select 1 from public.boxing_fighter_media m where m.fighter_id = f.id and m.review_state = 'approved')),
    'upcoming_fighters_without_approved_portrait', (select count(*) from fb where upcoming and not exists (select 1 from public.boxing_fighter_media m where m.fighter_id = fb.fighter_id and m.review_state = 'approved')),
    'video_channels', (select count(*) from public.boxing_video_channels),
    'video_channels_identity_verified', (select count(*) from public.boxing_video_channels where identity_state = 'verified'),
    'video_channels_rights_approved', (select count(*) from public.boxing_video_channels where rights_state = 'approved'),
    'video_channels_enabled', (select count(*) from public.boxing_video_channels where enabled),
    'video_channels_by_class', (select coalesce(jsonb_object_agg(source_class, n), '{}'::jsonb) from (select source_class, count(*) n from public.boxing_video_channels group by 1) x),
    'videos', (select count(*) from public.boxing_videos),
    'videos_by_type', (select coalesce(jsonb_object_agg(coalesce(video_type, 'null'), n), '{}'::jsonb) from (select video_type, count(*) n from public.boxing_videos group by 1) x),
    'video_links_by_entity', (select coalesce(jsonb_object_agg(entity_type, n), '{}'::jsonb) from (select entity_type, count(*) n from public.boxing_video_links group by 1) x)),
  'odds', jsonb_build_object(
    'provider_events', (select count(*) from public.boxing_provider_events),
    'provider_events_upcoming', (select count(*) from public.boxing_provider_events where last_commence_time >= now()),
    'provider_participants', (select count(*) from public.boxing_provider_participants),
    'participant_identities', (select count(*) from public.boxing_provider_participant_identities),
    'quote_series', (select count(*) from public.boxing_provider_quote_series),
    'quotes', (select count(*) from public.boxing_provider_quotes),
    'captures', (select count(*) from public.boxing_provider_captures),
    'credits_used_last_capture', (select credits_used from public.boxing_provider_captures order by requested_at desc limit 1),
    'markets_matched_to_bouts', (select count(*) from public.boxing_markets where bout_id is not null),
    'unmatched_open', (select count(*) from public.boxing_market_unmatched where not resolved),
    'unmatched_reasons', (select coalesce(jsonb_object_agg(reason, n), '{}'::jsonb) from (select reason, count(*) n from public.boxing_market_unmatched where not resolved group by 1) x)),
  'news', jsonb_build_object(
    'news_events_by_type', (select coalesce(jsonb_object_agg(event_type, n), '{}'::jsonb) from (select event_type, count(*) n from public.boxing_news_events group by 1) x),
    'news_events_by_state', (select coalesce(jsonb_object_agg(state, n), '{}'::jsonb) from (select state, count(*) n from public.boxing_news_events group by 1) x),
    'articles_by_state', (select coalesce(jsonb_object_agg(state, n), '{}'::jsonb) from (select state, count(*) n from public.boxing_articles group by 1) x)),
  'history', jsonb_build_object(
    'events_by_decade', (select coalesce(jsonb_object_agg(d, n), '{}'::jsonb) from (select (extract(year from event_date)::int / 10 * 10)::text || 's' d, count(*) n from ev where event_date is not null group by 1) x),
    'bouts_by_decade', (select coalesce(jsonb_object_agg(d, n), '{}'::jsonb) from (select (extract(year from e.event_date)::int / 10 * 10)::text || 's' d, count(*) n from b join ev e on e.id = b.event_id where e.event_date is not null group by 1) x),
    'fighters_by_decade_of_first_bout', (select coalesce(jsonb_object_agg(d, n), '{}'::jsonb) from (select (extract(year from m)::int / 10 * 10)::text || 's' d, count(*) n from (select fighter_id, min(event_date) m from fp group by 1) y group by 1) x),
    'venues_by_decade_of_event', (select coalesce(jsonb_object_agg(d, n), '{}'::jsonb) from (select (extract(year from event_date)::int / 10 * 10)::text || 's' d, count(distinct venue_id) n from ev where venue_id is not null group by 1) x),
    'title_reigns_by_decade_started', (select coalesce(jsonb_object_agg(d, n), '{}'::jsonb) from (select (extract(year from started_on)::int / 10 * 10)::text || 's' d, count(*) n from public.boxing_title_reigns where started_on is not null group by 1) x),
    'earliest_event_date', (select min(event_date) from ev),
    'latest_event_date', (select max(event_date) from ev),
    'hall_of_fame_modeled', exists (select 1 from pg_catalog.pg_tables where schemaname = 'public' and tablename like 'boxing\_hall%'),
    'persons_modeled', exists (select 1 from pg_catalog.pg_tables where schemaname = 'public' and tablename = 'boxing_persons'),
    'organization_media_modeled', exists (select 1 from pg_catalog.pg_tables where schemaname = 'public' and tablename = 'boxing_organization_media')),
  'sources', jsonb_build_object(
    'registry', (select coalesce(jsonb_agg(jsonb_build_object('source_key', s.source_key, 'kind', s.source_kind, 'access_mode', s.access_mode, 'rights_state', s.rights_state, 'enabled', s.enabled,
        'documents', (select count(*) from public.boxing_source_documents d where d.source_id = s.id),
        'observations', (select count(*) from public.boxing_source_observations x where x.source_id = s.id),
        'last_run_status', (select status from public.boxing_ingest_runs ir where ir.source_id = s.id order by started_at desc limit 1),
        'last_run_at', (select started_at from public.boxing_ingest_runs ir where ir.source_id = s.id order by started_at desc limit 1),
        'last_ok_at', (select max(started_at) from public.boxing_ingest_runs ir where ir.source_id = s.id and ir.status in ('ok','partial')),
        'scheduled_runs', (select count(*) from public.boxing_ingest_runs ir where ir.source_id = s.id and ir.trigger_type = 'scheduled')) order by s.source_kind, s.source_key), '[]'::jsonb)
      from public.boxing_sources s),
    'documents_by_source_and_parser', (select coalesce(jsonb_agg(jsonb_build_object('source_key', x.source_key, 'parser_version', x.parser_version, 'status', x.status, 'documents', x.n) order by x.source_key, x.parser_version), '[]'::jsonb)
      from (select s.source_key, rv.parser_version, d.status, count(*) n from public.boxing_source_documents d join public.boxing_sources s on s.id = d.source_id
            left join public.boxing_source_document_revisions rv on rv.document_id = d.id and rv.revision = d.current_revision group by 1, 2, 3) x),
    'worker_invocations_by_trigger', (select coalesce(jsonb_object_agg(worker || ':' || trigger_type, n), '{}'::jsonb) from (select worker, trigger_type, count(*) n from public.boxing_worker_invocations group by 1, 2) x))
)
