// GENERATED by scripts/media/derivatives.mjs — do not edit by hand.
//
// Derivative crops of APPROVED portraits only (scripts/media/portraits.json). The registry and
// boxing_fighter_media remain the source of truth for rights; this file only says which local crop exists for
// which shape, so the UI can pick the right one. Every url is a local /media/ path: nothing is hotlinked.

export const PORTRAIT_MANIFEST = {
 "generated_at": "2026-09-18T13:44:56.237Z",
 "variants": {
  "hero": {
   "aspect": 0.8,
   "width": 1000,
   "height": 1250
  },
  "card": {
   "aspect": 0.8,
   "width": 800,
   "height": 1000
  },
  "wide": {
   "aspect": 1.7777777777777777,
   "width": 1200,
   "height": 675
  },
  "square": {
   "aspect": 1,
   "width": 512,
   "height": 512
  },
  "avatar": {
   "aspect": 1,
   "width": 160,
   "height": 160
  }
 },
 "portraits": {
  "082996082a21": {
   "name": "Andres “Andy” Ruiz",
   "source": "/media/boxers/082996082a21.jpg",
   "source_width": 768,
   "source_height": 768,
   "sha256": "c412b147329815f97655e51e35bcfc03fbce9e14a2b1f3ed7d2c6077f440b296",
   "focus": "45% 20%",
   "variants": {
    "hero": {
     "url": "/media/boxers/082996082a21/hero.jpg",
     "width": 614,
     "height": 768,
     "bytes": 29672
    },
    "card": {
     "url": "/media/boxers/082996082a21/card.jpg",
     "width": 614,
     "height": 768,
     "bytes": 29672
    },
    "wide": {
     "url": "/media/boxers/082996082a21/wide.jpg",
     "width": 768,
     "height": 432,
     "bytes": 20815
    },
    "square": {
     "url": "/media/boxers/082996082a21/square.jpg",
     "width": 512,
     "height": 512,
     "bytes": 21679
    },
    "avatar": {
     "url": "/media/boxers/082996082a21/avatar.jpg",
     "width": 160,
     "height": 160,
     "bytes": 4830
    }
   }
  },
  "5bb57f06573c": {
   "name": "Teofimo Andres Lopez",
   "source": "/media/boxers/5bb57f06573c.jpg",
   "source_width": 617,
   "source_height": 485,
   "sha256": "f40c3b118f70c0ad10f3452af45c1ea8d75566b212893adfe99a0acb0f15663f",
   "focus": "50% 30%",
   "variants": {
    "hero": {
     "url": "/media/boxers/5bb57f06573c/hero.jpg",
     "width": 388,
     "height": 485,
     "bytes": 19967
    },
    "card": {
     "url": "/media/boxers/5bb57f06573c/card.jpg",
     "width": 388,
     "height": 485,
     "bytes": 19967
    },
    "wide": {
     "url": "/media/boxers/5bb57f06573c/wide.jpg",
     "width": 617,
     "height": 347,
     "bytes": 25636
    },
    "square": {
     "url": "/media/boxers/5bb57f06573c/square.jpg",
     "width": 485,
     "height": 485,
     "bytes": 25865
    },
    "avatar": {
     "url": "/media/boxers/5bb57f06573c/avatar.jpg",
     "width": 160,
     "height": 160,
     "bytes": 5975
    }
   }
  },
  "7175c0735be1": {
   "name": "Anthony David Benavidez",
   "source": "/media/boxers/7175c0735be1.jpg",
   "source_width": 546,
   "source_height": 680,
   "sha256": "353a3928c1fb899b92ee01b3edf8fa5cb1b08aa983564703151a283447785e06",
   "focus": "center",
   "variants": {
    "hero": {
     "url": "/media/boxers/7175c0735be1/hero.jpg",
     "width": 544,
     "height": 680,
     "bytes": 23637
    },
    "card": {
     "url": "/media/boxers/7175c0735be1/card.jpg",
     "width": 544,
     "height": 680,
     "bytes": 23637
    },
    "wide": {
     "url": "/media/boxers/7175c0735be1/wide.jpg",
     "width": 546,
     "height": 307,
     "bytes": 13316
    },
    "square": {
     "url": "/media/boxers/7175c0735be1/square.jpg",
     "width": 512,
     "height": 512,
     "bytes": 19006
    },
    "avatar": {
     "url": "/media/boxers/7175c0735be1/avatar.jpg",
     "width": 160,
     "height": 160,
     "bytes": 4465
    }
   }
  },
  "9856a86deb1e": {
   "name": "Keith Fitzgerald Thurman",
   "source": "/media/boxers/9856a86deb1e.jpg",
   "source_width": 894,
   "source_height": 914,
   "sha256": "79c33b71a8b5c4a8dbc59bc3b7e55d9e8ae617f5c9afe10913c84f3e0f2f1f6f",
   "focus": "82% 22%",
   "variants": {
    "hero": {
     "url": "/media/boxers/9856a86deb1e/hero.jpg",
     "width": 731,
     "height": 914,
     "bytes": 71031
    },
    "card": {
     "url": "/media/boxers/9856a86deb1e/card.jpg",
     "width": 731,
     "height": 914,
     "bytes": 71031
    },
    "wide": {
     "url": "/media/boxers/9856a86deb1e/wide.jpg",
     "width": 894,
     "height": 503,
     "bytes": 45763
    },
    "square": {
     "url": "/media/boxers/9856a86deb1e/square.jpg",
     "width": 512,
     "height": 512,
     "bytes": 38967
    },
    "avatar": {
     "url": "/media/boxers/9856a86deb1e/avatar.jpg",
     "width": 160,
     "height": 160,
     "bytes": 6830
    }
   }
  },
  "6c9377da556f": {
   "name": "Carlos Adames",
   "source": "/media/boxers/6c9377da556f.jpg",
   "source_width": 850,
   "source_height": 1100,
   "sha256": "21a82fa69de935b410138ff0618f99f70e696005255b6229e1a968d0b6aed410",
   "focus": "50% 12%",
   "variants": {
    "hero": {
     "url": "/media/boxers/6c9377da556f/hero.jpg",
     "width": 850,
     "height": 1063,
     "bytes": 116733
    },
    "card": {
     "url": "/media/boxers/6c9377da556f/card.jpg",
     "width": 800,
     "height": 1000,
     "bytes": 94085
    },
    "wide": {
     "url": "/media/boxers/6c9377da556f/wide.jpg",
     "width": 850,
     "height": 478,
     "bytes": 56141
    },
    "square": {
     "url": "/media/boxers/6c9377da556f/square.jpg",
     "width": 512,
     "height": 512,
     "bytes": 37708
    },
    "avatar": {
     "url": "/media/boxers/6c9377da556f/avatar.jpg",
     "width": 160,
     "height": 160,
     "bytes": 7099
    }
   }
  },
  "797a3bfa8f21": {
   "name": "Cherneka Johnson",
   "source": "/media/boxers/797a3bfa8f21.jpg",
   "source_width": 543,
   "source_height": 855,
   "sha256": "fa8a4b8ebd0a1fc1da15b997d96045c0ca683f5922c833d3688609ce729af7e6",
   "focus": "top",
   "variants": {
    "hero": {
     "url": "/media/boxers/797a3bfa8f21/hero.jpg",
     "width": 543,
     "height": 679,
     "bytes": 36562
    },
    "card": {
     "url": "/media/boxers/797a3bfa8f21/card.jpg",
     "width": 543,
     "height": 679,
     "bytes": 36562
    },
    "wide": {
     "url": "/media/boxers/797a3bfa8f21/wide.jpg",
     "width": 543,
     "height": 305,
     "bytes": 17805
    },
    "square": {
     "url": "/media/boxers/797a3bfa8f21/square.jpg",
     "width": 512,
     "height": 512,
     "bytes": 28140
    },
    "avatar": {
     "url": "/media/boxers/797a3bfa8f21/avatar.jpg",
     "width": 160,
     "height": 160,
     "bytes": 6038
    }
   }
  },
  "3808374f51a8": {
   "name": "Oleksandr Gvozdyk",
   "source": "/media/boxers/3808374f51a8.jpg",
   "source_width": 900,
   "source_height": 1064,
   "sha256": "2f287e850f6e813aeee20d4f8aa3a9f0b1cc2e79635c6ae1bd2155bb75288ab6",
   "focus": "top",
   "variants": {
    "hero": {
     "url": "/media/boxers/3808374f51a8/hero.jpg",
     "width": 851,
     "height": 1064,
     "bytes": 194731
    },
    "card": {
     "url": "/media/boxers/3808374f51a8/card.jpg",
     "width": 800,
     "height": 1000,
     "bytes": 173407
    },
    "wide": {
     "url": "/media/boxers/3808374f51a8/wide.jpg",
     "width": 900,
     "height": 506,
     "bytes": 76119
    },
    "square": {
     "url": "/media/boxers/3808374f51a8/square.jpg",
     "width": 512,
     "height": 512,
     "bytes": 66717
    },
    "avatar": {
     "url": "/media/boxers/3808374f51a8/avatar.jpg",
     "width": 160,
     "height": 160,
     "bytes": 8883
    }
   }
  },
  "671308131e5c": {
   "name": "Israil Madrimov",
   "source": "/media/boxers/671308131e5c.jpg",
   "source_width": 431,
   "source_height": 515,
   "sha256": "288fc104c09c186cc5cb91e803548edc1d2c108b7a38881ef7f30ac807b04a93",
   "focus": "top",
   "variants": {
    "hero": {
     "url": "/media/boxers/671308131e5c/hero.jpg",
     "width": 412,
     "height": 515,
     "bytes": 21771
    },
    "card": {
     "url": "/media/boxers/671308131e5c/card.jpg",
     "width": 412,
     "height": 515,
     "bytes": 21771
    },
    "wide": {
     "url": "/media/boxers/671308131e5c/wide.jpg",
     "width": 431,
     "height": 242,
     "bytes": 12373
    },
    "square": {
     "url": "/media/boxers/671308131e5c/square.jpg",
     "width": 431,
     "height": 431,
     "bytes": 19291
    },
    "avatar": {
     "url": "/media/boxers/671308131e5c/avatar.jpg",
     "width": 160,
     "height": 160,
     "bytes": 5073
    }
   }
  },
  "b47fbf71fb6b": {
   "name": "Guillermo Rigondeaux",
   "source": "/media/boxers/b47fbf71fb6b.jpg",
   "source_width": 768,
   "source_height": 768,
   "sha256": "3e50e150f0116788df246e3cd23a825e8e23ebf21c14fc0750e30ed7cfd76b3a",
   "focus": "50% 30%",
   "variants": {
    "hero": {
     "url": "/media/boxers/b47fbf71fb6b/hero.jpg",
     "width": 614,
     "height": 768,
     "bytes": 59518
    },
    "card": {
     "url": "/media/boxers/b47fbf71fb6b/card.jpg",
     "width": 614,
     "height": 768,
     "bytes": 59518
    },
    "wide": {
     "url": "/media/boxers/b47fbf71fb6b/wide.jpg",
     "width": 768,
     "height": 432,
     "bytes": 37905
    },
    "square": {
     "url": "/media/boxers/b47fbf71fb6b/square.jpg",
     "width": 512,
     "height": 512,
     "bytes": 42477
    },
    "avatar": {
     "url": "/media/boxers/b47fbf71fb6b/avatar.jpg",
     "width": 160,
     "height": 160,
     "bytes": 8039
    }
   }
  },
  "e570a57b0038": {
   "name": "Hebert Conceicao Sousa",
   "source": "/media/boxers/e570a57b0038.jpg",
   "source_width": 768,
   "source_height": 768,
   "sha256": "ccf6bf07e0f7eaeb66b0de1f1ca560c5251c55ae27957f4f09125178638d485b",
   "focus": "50% 30%",
   "variants": {
    "hero": {
     "url": "/media/boxers/e570a57b0038/hero.jpg",
     "width": 614,
     "height": 768,
     "bytes": 46189
    },
    "card": {
     "url": "/media/boxers/e570a57b0038/card.jpg",
     "width": 614,
     "height": 768,
     "bytes": 46189
    },
    "wide": {
     "url": "/media/boxers/e570a57b0038/wide.jpg",
     "width": 768,
     "height": 432,
     "bytes": 28883
    },
    "square": {
     "url": "/media/boxers/e570a57b0038/square.jpg",
     "width": 512,
     "height": 512,
     "bytes": 32234
    },
    "avatar": {
     "url": "/media/boxers/e570a57b0038/avatar.jpg",
     "width": 160,
     "height": 160,
     "bytes": 6957
    }
   }
  },
  "c6a650eb83c5": {
   "name": "Ryan Garcia",
   "source": "/media/boxers/c6a650eb83c5.jpg",
   "source_width": 768,
   "source_height": 768,
   "sha256": "f64c137c6c39929179c1e2ab039c5f51263dd8f1d1ac42a07e24170da0e150f8",
   "focus": "50% 30%",
   "variants": {
    "hero": {
     "url": "/media/boxers/c6a650eb83c5/hero.jpg",
     "width": 614,
     "height": 768,
     "bytes": 39491
    },
    "card": {
     "url": "/media/boxers/c6a650eb83c5/card.jpg",
     "width": 614,
     "height": 768,
     "bytes": 39491
    },
    "wide": {
     "url": "/media/boxers/c6a650eb83c5/wide.jpg",
     "width": 768,
     "height": 432,
     "bytes": 28395
    },
    "square": {
     "url": "/media/boxers/c6a650eb83c5/square.jpg",
     "width": 512,
     "height": 512,
     "bytes": 27621
    },
    "avatar": {
     "url": "/media/boxers/c6a650eb83c5/avatar.jpg",
     "width": 160,
     "height": 160,
     "bytes": 5918
    }
   }
  }
 }
} as const;

export default PORTRAIT_MANIFEST;
